name: upgrad
channels:
  - defaults
dependencies:
  - python=3.10
  - ipykernel
  - pip:
      - matplotlib==3.8.0
      - numpy==1.26.1
      - pandas==2.1.1
      - seaborn==0.13.0
      - statsmodels==0.14.0
      - scikit-learn==1.3.2
      - imbalanced-learn==0.12.0